version: '3.5'

services:
  redcap-linter-server:
    container_name: redcap-linter-server
    restart: always
    image: redcap-linter-server
    build: .
    command:
      - "flask"
      - "run"
      - "--host=0.0.0.0"
    ports:
      - "5000:5000"
    networks:
      - custom
    volumes:
      - ./server:/home/app-user/app/server
    environment:
      - FLASK_APP=server/app.py
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8

  redcap-linter-client:
    container_name: redcap-linter-client
    image: redcap-linter-server
    command:
      - "npm"
      - "start"
      - "--prefix"
      - "web/"
    volumes:
      - './web:/home/app-user/app/web'
      - '/home/app-user/app/web/node_modules'
    ports:
      - "3000:3000"
    networks:
      - custom
    depends_on:
      - "redcap-linter-server"
    environment:
      - NODE_ENV=development
      - NODE_PATH=./src

networks:
  custom:
    driver: bridge
    ipam:
      config:
        - subnet: "10.10.11.1/24"
