redcap_urls:
  - redcap_base_url: https://redcapdev.mskcc.org/api/
    env: Dev
  - redcap_base_url: https://redcaptest.mskcc.org/api/
    env: Test
    default: true
  - redcap_base_url: https://redcap.mskcc.org/api/
    env: Production
